### ISSUE TITLE
Moves edit

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-api#101]
# User story
As an API consumer I want to be able to edit moves of a GeoKret because it's the purpose of the service.

# Acceptance criteria
- [x] The GeoKret owner MUST be able to edit a move
- [x] The move author MUST be able to edit a move
- [x] An admin MUST be able to edit a move
- [x] A move MUST be selected by it's id
- [x] The `move type` CAN be changed
- [x] On `move type` change coordinates presence MUST be checked
- [x] The operation MUST be secured using tracking-code if not coming from an authenticated move type
- [x] The concerned GeoKret CAN be changed
- [x] The move date time CAN be changed
- [x] The move comment CAN be changed
- [x] The move author CANNOT be changed except by admin
- [x] The `distance` of the *old* GeoKret moves MUST reevaluated* asynchronously
- [x] The `distance` of the *new* GeoKret moves MUST reevaluated* asynchronously
- [ ] The missing status field of the *old* GeoKret MUST be reevaluated*
- [ ] The missing status field of the *new* GeoKret MUST be reevaluated*
- [ ] The *old* GeoKret altitude profile MUST be reevaluated* asynchronously #88
- [ ] The *new* GeoKret altitude profile MUST be reevaluated* asynchronously #88
- [ ] The *old* GeoKret country track MUST be reevaluated* asynchronously #89
- [ ] The *new* GeoKret country track MUST be reevaluated* asynchronously #89
- [x] The comment MUST accept a subset of authorized html tags

# Remarks
* Intensive compute operation or operations requiring an external service must be realized asynchronously
* **If the move type is changed, the new move rules MUST be applied See #95 #96 #97 #98 #99 #100 #80**
